export const Endpoints = {
  signIn: '/auth/signin',
  signUp: '/auth/signup',
  getIndustries: '/industries',
  getIndustry: (id: number) => `/industries/${id}`,
  postIndustries: '/industries',
  putIndustry: (id: number) => `/industry/${id}`,
  deleteIndustry: (id: number) => `/industry/${id}`,
  getCategories: '/categories',
  getCategory: (id: number) => `/categories/${id}`,
  postCategories: '/categories',
  putCategory: (id: number) => `/category/${id}`,
  deleteCategory: (id: number) => `/category/${id}`,
  getJobs: '/jobs',
  getJob: (id: number) => `/jobs/${id}`,
  postJobs: '/jobs',
  putJob: (id: number) => `/jobs/${id}`,
  deleteJob: (id: number) => `/jobs/${id}`,
};
